name: bloc_demo
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  bloc: ^5.0.0
  cupertino_icons: ^0.1.3
  equatable: ^1.2.0
  flutter_bloc: ^5.0.0
  shared_preferences: ^0.5.7+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
